name: bdcallingtaskmanagerapp
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7 
  google_nav_bar: ^5.0.7
  table_calendar: ^3.2.0
  get_it: ^7.6.0
  get: ^4.6.6
  http: ^1.1.0
  shared_preferences: ^2.2.2
  logger: ^2.6.1 
  awesome_dialog: ^3.2.1
  dio: ^5.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^5.0.0


flutter:

 
  uses-material-design: true

 
  assets:
    - assets/images/
    - assets/images/bg.png


  fonts:
    - family: Chakra Petch
      fonts:
        - asset: assets/fonts/ChakraPetch-Regular.ttf
          weight: 400  # Normal/Regular (default)
        - asset: assets/fonts/ChakraPetch-Medium.ttf
          weight: 500  # Medium weight
        - asset: assets/fonts/ChakraPetch-Italic.ttf
          style: italic  # Italic variant
    

 